CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    roll VARCHAR(50) UNIQUE NOT NULL,
    webmail VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
